import { Box, CssBaseline, GlobalStyles, ThemeProvider } from "@mui/material";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v15-appRouter";
import type { Metadata } from "next";
import AuthProvider from "~/components/AuthProvider";
import Sidebar from "~/components/layout/Sidebar";
import ProtectedRoute from "~/components/ProtectedRoute";
import ReactQueryProvider from "~/components/ReactQueryProvider";
import theme from "~/theme/dark";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body cz-shortcut-listen="true">
        <AppRouterCacheProvider options={{ key: "css" }}>
          <AuthProvider>
            <ProtectedRoute>
              <ThemeProvider theme={theme}>
                <GlobalStyles
                  styles={{
                    body: {
                      margin: 0,
                      padding: 0,
                    },
                  }}
                />
                <CssBaseline>
                  <ReactQueryProvider>
                    {children}
                  </ReactQueryProvider>
                </CssBaseline>
              </ThemeProvider>
            </ProtectedRoute>
          </AuthProvider>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
